language: java
dist: bionic
install:
  - curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
  - java -jar BuildTools.jar --rev 1.13.2
  - java -jar BuildTools.jar --rev 1.16.3
  - java -jar BuildTools.jar --rev 1.16.5
  - mvn -B install:install-file -Dfile=spigot-1.13.2.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.13.2-R0.1-SNAPSHOT -Dpackaging=jar
  - mvn -B install:install-file -Dfile=spigot-1.16.3.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.16.3-R0.1-SNAPSHOT -Dpackaging=jar
  - mvn -B install:install-file -Dfile=spigot-1.16.5.jar -DgroupId=org.spigotmc -DartifactId=spigot -Dversion=1.16.5-R0.1-SNAPSHOT -Dpackaging=jar
script: 
  - mvn -B CompressedBlocksPlugin
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: "target/CompressedBlocksPlugin.jar"
  skip_cleanup: true
  on:
    tags: true
